/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class shell_game_jpsplus_JPSPlus */

#ifndef _Included_shell_game_jpsplus_JPSPlus
#define _Included_shell_game_jpsplus_JPSPlus
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     shell_game_jpsplus_JPSPlus
 * Method:    save
 * Signature: ([ZIIILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_shell_game_jpsplus_JPSPlus_save
  (JNIEnv *, jclass, jbooleanArray, jint, jint, jint, jstring);

/*
 * Class:     shell_game_jpsplus_JPSPlus
 * Method:    load
 * Signature: (ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_shell_game_jpsplus_JPSPlus_load
  (JNIEnv *, jclass, jint, jstring);

/*
 * Class:     shell_game_jpsplus_JPSPlus
 * Method:    find
 * Signature: (ISSSS)[I
 */
JNIEXPORT jintArray JNICALL Java_shell_game_jpsplus_JPSPlus_find
  (JNIEnv *, jclass, jint, jshort, jshort, jshort, jshort);

/*
 * Class:     shell_game_jpsplus_JPSPlus
 * Method:    walkable
 * Signature: (ISS)Z
 */
JNIEXPORT jboolean JNICALL Java_shell_game_jpsplus_JPSPlus_walkable
  (JNIEnv *, jclass, jint, jshort, jshort);

#ifdef __cplusplus
}
#endif
#endif
